### ISSUE TITLE
Dump not found in android fs

### ISSUE THREAD

**Issue by espilioto** [tuya-cloudcutter/lightleak#22]
So, managed to complete the steps and am searching for the dump to upload.
Unfortunately the app does not create its directory in /data (or any place of that matter).
Also the my dumps tab does not work, probably because of that.
Checked if the app requested additional permissions, but it did not.

Any ideas?
![image](https://github.com/tuya-cloudcutter/lightleak/assets/8510006/fa0c4b8b-8cb0-42f5-8a84-c32e3a4d28fe)

**Comment by kuba2k2** [comment]
Try `/sdcard/Android/data/` instead of `/data`. The path is visible on the screen.

**Comment by espilioto** [comment]
Yup, just noticed as well.
The file manager pulled a fast one on me 😂
