### ISSUE TITLE
customap platformio build failed with esp32, others works fine.

### ISSUE THREAD

**Issue by remlei** [tuya-cloudcutter/lightleak#5]
Processing esp32 (platform: espressif32; board: esp32dev; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.3.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20006.221224 (2.0.6)
 - tool-esptoolpy @ 1.40400.0 (4.4.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 34 compatible libraries
Scanning dependencies...
Dependency Graph
|-- CRC32 @ 2.0.0
|-- WiFi @ 2.0.0
Building in release mode
Compiling .pio\build\esp32\src\customap.cpp.o
Archiving .pio\build\esp32\lib77d\libCRC32.a
Compiling .pio\build\esp32\lib961\WiFi\WiFiClient.cpp.o
Compiling .pio\build\esp32\lib961\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\esp32\lib961\WiFi\WiFiMulti.cpp.o
src/customap.cpp: In function 'void setup()':
src/customap.cpp:15:63: error: no matching function for call to 'WiFiClass::onEvent(void (&)(arduino_event_id_t), system_event_id_t)'
  WiFi.onEvent(onStationConnected, SYSTEM_EVENT_AP_STACONNECTED);
                                                               ^
In file included from .platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiSTA.h:28,
                 from .platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFi.h:32,
                 from include/customap.h:11,
                 from src/customap.cpp:1:
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:159:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventCb, arduino_event_id_t)'
     wifi_event_id_t onEvent(WiFiEventCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:159:21: note:   no known conversion for argument 2 from 'system_event_id_t' to 'arduino_event_id_t'
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:160:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventFuncCb, arduino_event_id_t)'      
     wifi_event_id_t onEvent(WiFiEventFuncCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:160:21: note:   no known conversion for argument 1 from 'void(arduino_event_id_t)' to 'WiFiEventFuncCb' {aka 'std::function<void(arduino_event_id_t, arduino_event_info_t)>'}
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:161:21: note: candidate: 'wifi_event_id_t WiFiGenericClass::onEvent(WiFiEventSysCb, arduino_event_id_t)'       
     wifi_event_id_t onEvent(WiFiEventSysCb cbEvent, arduino_event_id_t event = ARDUINO_EVENT_MAX);
                     ^~~~~~~
.platformio/packages/framework-arduinoespressif32/libraries/WiFi/src/WiFiGeneric.h:161:21: note:   no known conversion for argument 2 from 'system_event_id_t' to 'arduino_event_id_t'
*** [.pio\build\esp32\src\customap.cpp.o] Error 1
========================================================================================== [FAILED] Took 8.43 seconds ==========================================================================================

**Comment by remlei** [comment]
using visual studio code with platformio extension on windows 10

**Comment by Cossid** [comment]
Looks like Espressif cleaned out some legacy stuff and changed their wifi event enum to be more arduinio standard.

Try changing src/customap.cpp line 15 to be the same as line 19: `WiFi.onEvent(onStationConnected, ARDUINO_EVENT_WIFI_AP_STACONNECTED);`
