### ISSUE TITLE
Garbage characters being shown in VSCode

### ISSUE THREAD

**Issue by ElGranPepo** [tuya-cloudcutter/lightleak#9]
Using WEMOS D1 ESP8266.  when using upload and monitor seeing garbage characters in monitor.

![image](https://user-images.githubusercontent.com/60438864/213877564-4ce0cd2d-fc8b-4938-a489-0a78edede048.png)

**Comment by kuba2k2** [comment]
Is that a problem? The program prints out the wifi password, which is not fully ASCII.

**Comment by ElGranPepo** [comment]
not a problem but trying to resolve issue to better see output, any ideas/recommendations?

**Comment by kuba2k2** [comment]
You can use PuTTY or some other proper terminal application.

**Comment by ElGranPepo** [comment]
same issue, but im guessing you are saying this is unrelated to the actual firmware being uploaded.  will close but wanted to post for other that might see this.

![image](https://user-images.githubusercontent.com/60438864/213887260-59bd6c1c-01e1-4b46-9525-7a4e42c77a43.png)

**Comment by kuba2k2** [comment]
I think the garbage characters at the beginning is just ESP8266's bootloader transmitting something at a different baudrate (38400 AFAIK). Try setting to 38400 and see if there's anything readable.
